# Generated by Django 3.2 on 2021-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='extra', max_length=255),
        ),
    ]
